### ISSUE TITLE
Recognize "twitter.com" and "http://twitter.com" as duplicate links

### ISSUE THREAD

**Issue by michellai** [nozbzh/urlshortener#2]
Optimize database storage so that links with different prefixes are stored as 1 entry.

e.g. "www.twitter.com" and "twitter.com", "https://www.google.com" and "http://google.com"

**Comment by michellai** [comment]
and "twitter.com/" and "twitter.com"

**Comment by nozbzh** [comment]
Fixed in 8a7210c0d20679a6217e9edc87b45a792c4e761a
